Scaler -> Scaler is a single number without direction
Vectors -> Vectors is a list of number. it can have only single row or only single column
Matrix -> Matrix can have multiple rows and multiple columns

In [1]:
import numpy as np

In [2]:
matrix_1 = np.asarray([[2, 3],[6, 7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_2 = np.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# matrix with random values
random_matrix = np.random.randint(100, size = (4,5))
print(random_matrix)

[[15 12 41 76 40]
 [ 5 85 26 24 45]
 [48 93 18 87 35]
 [10 29 68 42 84]]


In [5]:
# Matrix with all the values as 1
matrix_3 = np.ones((2, 3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
matrix_3 = np.ones((10, 10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [12]:
null_matrix = np.zeros((4, 4), dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
# Identity Matrix
identity_matrix = np.eye(5,5, dtype=int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [13]:
# Transpose of a Matrix
a = np.random.randint(100, size=(4, 5))
print(a)

[[66 55 90 96 90]
 [76 35  2 84 42]
 [ 0 52 79 57 82]
 [17 38  2 23 70]]


In [14]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[66 76  0 17]
 [55 35 52 38]
 [90  2 79  2]
 [96 84 57 23]
 [90 42 82 70]]


In [16]:
a = np.asarray([[2, 3], [4, 5]])
b = np.asarray([[4, 5], [6, 7]])
print(a)
print(b)
print('sum = ', a+b)

[[2 3]
 [4 5]]
[[4 5]
 [6 7]]
sum =  [[ 6  8]
 [10 12]]


In [39]:
a = np.asarray([[2, 3], [4, 5]])
b = np.asarray([[4, 5], [6, 7]])
print(a)
print(b)
print('diff = ', a-b)

[[2 3]
 [4 5]]
[[4 5]
 [6 7]]
diff =  [[-2 -2]
 [-2 -2]]


In [21]:
# we can only add two matrix if they are of same shape
# operands could not be broadcast together with shapes (3,3) (3,4) 
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(10, size=(3,3))
sum = np.add(matrix_1, matrix_2)
print(matrix_1)
print(matrix_2)
print(sum)

[[0 8 7]
 [9 4 4]
 [2 4 4]]
[[4 8 0]
 [1 8 1]
 [7 1 1]]
[[ 4 16  7]
 [10 12  5]
 [ 9  5  5]]


In [23]:
diff = np.subtract(matrix_1, matrix_2)
print(diff)

[[-4  0  7]
 [ 8 -4  3]
 [-5  3  3]]


In [26]:
# multiplication with scaler 
x = 5
y = np.random.randint(10, size=(4,4))
product = np.multiply(x, y)
print(y)
print(product)

[[9 6 5 2]
 [7 4 0 2]
 [8 0 5 3]
 [0 2 8 1]]
[[45 30 25 10]
 [35 20  0 10]
 [40  0 25 15]
 [ 0 10 40  5]]


In [27]:
# Multiplying 2 Matrices
matrix_1 = np.random.randint(5, size=(3, 3))
matrix_2 = np.random.randint(5, size=(3, 4))
print(matrix_1)

[[0 2 2]
 [3 1 3]
 [0 3 0]]


In [28]:
print(matrix_2)

[[2 3 4 0]
 [3 0 0 4]
 [3 1 4 3]]


In [29]:
product = np.dot(matrix_1, matrix_2)
print(product)

[[12  2  8 14]
 [18 12 24 13]
 [ 9  0  0 12]]


In [35]:
# Element wise Matrix Multiplication -> both matrix should have same shape
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [36]:
print(matrix_3)

[[4 0 4]
 [1 0 1]
 [3 4 1]]


In [37]:
print(matrix_4)

[[3 4 1]
 [4 4 3]
 [1 3 1]]


In [38]:
product = np.multiply(matrix_3, matrix_4)
print(product)

[[12  0  4]
 [ 4  0  3]
 [ 3 12  1]]
